(keyboard-translate ?\C-h ?\C-?)
(setq make-backup-files nil)
(setq auto-save-default nil)
(if (file-exists-p "/usr/local/Cellar/erlang/21.3.5/lib/erlang/")
    (let ((erlang-dir "/usr/local/Cellar/erlang/21.3.5/lib/erlang/"))
      (setq load-path (cons (concat erlang-dir "lib/tools-3.1/emacs") load-path))
      (require 'erlang-start)
      (setq erlang-root-dir erlang-dir)
      (setq exec-path (cons erlang-dir exec-path))
      (setq erlang-man-root-dir (concat erlang-dir "man"))))
